### ISSUE TITLE
thumbnail for audio and video does not work

### ISSUE THREAD

**Issue by lduboeuf** [ubports/thumbnailer#3]
When it comes to display a thumbnail for an audio or a video, i got this:

> Thumbnailer: RequestImpl::dbusCallFinished(): D-Bus error: Handler::createFinished(): could not get thumbnail for thumbnail: /home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/HubIncoming/8/video20200423_140530245.mp4 (200,200): ERROR

here dbus-log, it seems that `vs-thumb` failed on guessing the type:

> vs-thumb: /build/thumbnailer-2.5+ubports1+0~20200219154510.1~1.gbpa4387b/src/vs-thumb/vs-thumb.cpp:49: void {anonymous}::extract_thumbnail(const QUrl&, const QUrl&): Assertion `extractor.has_video()' failed.
thumbnailer-service: [15:40:50.170] Critical: LocalThumbnailRequest::fetch(): ImageExtractor::read(): /usr/lib/arm-linux-gnueabihf/thumbnailer/vs-thumb crashed
thumbnailer-service: [15:40:50.171] Warning: "Handler::createFinished(): could not get thumbnail for thumbnail: /home/phablet/.cache/com.ubuntu.messaging-app/MessagingApp/HubIncoming/9/video20200423_140530245.mp4 (200,200): ERROR"

playing manually with `vs-thumb` lead to the same:

> /usr/lib/arm-linux-gnueabihf/thumbnailer/vs-thumb file:///home/phablet/Documents/test.ogg file:///home/phablet/Documents/titi.tiff
vs-thumb: /home/lduboeuf/thumbnailer/src/vs-thumb/vs-thumb.cpp:49: void {anonymous}::extract_thumbnail(const QUrl&, const QUrl&): Assertion `extractor.has_video()' failed.
Aborted

Note that `vs-thumb` tests with crossbuilder vm  went fine

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-thumbnailer/-/issues/3
